### ISSUE TITLE
GayatriChalisa & KaliMaaChalisa not loading properly

### ISSUE THREAD

**Issue by pratik-lal** [pratik-lal/VedicsSangrah#1]
Asset (.htm), Layout and activity has been added successfully for GayatriChalisa & KaliMaaChalisa but they are not working they are not working properly.

1. Check ChalisaMainPage button link configuration
2. If above doesn't work then create new Layout and Activity for GayatriChalisa & KaliMaaChalisa. Delete existing one.

**Comment by monkkitarp** [comment]
Update:
**ChalisaSangrah.cs** Activity was incorrectly updated on button14.  This button click option was referring to button 12.
This has been corrected. Application is functioning as expected now.
